### ISSUE TITLE
Django 1.11 Python3 support?

### ISSUE THREAD

**Issue by elcolie** [cipriantarta/django-logging#11]
Is it support Django 1.11 and Python3.6.2?

**Comment by cipriantarta** [comment]
@elcolie yes it does, in fact I'm currently using it with Django 1.11.5 and python 3.6.3

**Comment by elcolie** [comment]
Thank you for you fast response!

Off topic `http://cipriantarta.ro`  your website is down

**Comment by cipriantarta** [comment]
Hah, I know, I use it for mailing only ;)
