### ISSUE TITLE
Can not see the log?

### ISSUE THREAD

**Issue by elcolie** [cipriantarta/django-logging#14]
I am experimenting with my #13 
But I am not sure that how long does it take to let program take note on `file`
I have hit django for serveral times, but no file at all.

**Comment by cipriantarta** [comment]
The logs should be visible immediately after a request. Did you add the MIDDLEWARE class?
Also, the `app.log`, `debug.log`, `sql.log` should be created automatically after a server restart if they don'y exist.
If you do this:
`./manage.py shell`

`
from django_logging import log
`
`
log.debug("Hello")
`

Do you see anything?

**Comment by elcolie** [comment]
```bash
>>> from django_logging import log
>>> log.debug("Hello")
[DEBUG - 1507185359.393895] file:<console>.py, func:<module>, ln:1: Hello
```

**Comment by elcolie** [comment]
```python
DJANGO_LOGGING = {
    "CONSOLE_LOG": True,
    "SQL_LOG": True,
    "LOG_LEVEL": 'debug',  # - If settings.DEBUG is set to True, otherwise LOG_LEVEL is set to 'info'
    "DISABLE_EXISTING_LOGGERS": True,  # Set this to False if you want to combine with multiple loggers.
    "LOG_PATH": '{}/logs'.format(BASE_DIR),  # If the logs folder does not exist, it will be created.

    "IGNORED_PATHS": ['/admin', '/static', '/favicon.ico'],  # List of URL endpoints to ignore.

    "RESPONSE_FIELDS": ('status', 'reason', 'charset', 'headers', 'content'),  # List of response fields to log.

    "CONTENT_JSON_ONLY": True,  # Log response content only if its a JSON document.

    "ROTATE_MB": 100,  # Maximum size in MB that the log file can have before it gets rotated.

    "ROTATE_COUNT": 10,  # Maximum number of rotated log files.

    "INDENT_CONSOLE_LOG": 2,  # Indent console log by "n" spaces.

    "ELASTICSEARCH_ENABLED": False,  # Set to yes to enable elasticsearch support.

    "ELASTICSEARCH_HOSTS": ["localhost"],  # Elasticsearch hosts

    "ELASTICSEARCH_INDEX": "django-logging-json",  # Elasticsearch index name

    "ELASTICSEARCH_SSL": False,  # Elasticsearch connection via SSL (:443)

    "ELASTICSEARCH_AUTH": None,  # Elasticsearch authorization credentials (user, password)

}
```

From `shell` it does show up, but from `RESTful` it does not.
Only `debug.log`. `app.log` and `sql.log` are blank.

![image](https://user-images.githubusercontent.com/18206728/31214113-f9236a44-a9d3-11e7-9476-a6bee0e01ac7.png)

**Comment by cipriantarta** [comment]
app.log and sql.log are empty unless DEBUG=False. They are meant for production only

**Comment by elcolie** [comment]
I just change `DEBUG` to `False`
RESTful has not been any `request` log

**Comment by cipriantarta** [comment]
Did you add this in your `settings.py` file?
MIDDLEWARE_CLASSES = (
    'django_logging.middleware.DjangoLoggingMiddleware',
    ...
)

**Comment by elcolie** [comment]
Yes I did.
```python
# Middleware
MIDDLEWARE = [
    'django_logging.middleware.DjangoLoggingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
```
Any of them conflict with yours?

**Comment by elcolie** [comment]
I just change ` "CONTENT_JSON_ONLY": True,` to `False`. The log files are not change at all.

**Comment by cipriantarta** [comment]
Try adding it at the end of your middleware list.
If that still doesn’t work, put a breakpoint in django_logging/middleware.py on line 14 and see what happens.

**Comment by elcolie** [comment]
```python
class DjangoLoggingMiddleware(MiddlewareMixin):
    def process_exception(self, request, exception):
        error = ErrorLogObject(request, exception)
        log.error(error)

    def process_response(self, request, response):
        for connection in connections.all():
            self.log_connection_queries(connection)

        if request.path_info.startswith(tuple(settings.IGNORED_PATHS)):
            return response

        if response.status_code == 500:
            return response
        elif 400 <= response.status_code < 500:
            log.warning(LogObject(request, response))
        else:
            log.info(LogObject(request, response))
        return response

    def log_connection_queries(self, connection):
        for query in connection.queries:
            log.debug(SqlLogObject(query, connection.alias))
```

**Case:**
`request/response` is a valid `201` object. I can create an instance

connections
<django.db.utils.ConnectionHandler object at 0x10d456cf8>
On line 29 in the method `log_connection_queries`.
`connection.queries` is a blank array!

**Comment by cipriantarta** [comment]
If connection.queries is a blank array, then it’s beyond the scope of this library. You have to investigate why that is empty. Maybe the engine you use does not populate that, or maybe they get cleared before the code reaches this middleware.

**Comment by cipriantarta** [comment]
Did you manage to get it work in the end?

**Comment by elcolie** [comment]
No. I gave up and made my own customized middleware.
