### ISSUE TITLE
[BUG] Missing install requirement of certifi

### ISSUE THREAD

**Issue by FraBle** [cipriantarta/django-logging#16]
[`certifi` gets imported](https://github.com/cipriantarta/django-logging/blob/master/django_logging/handlers.py#L13), but [not installed with the library](https://github.com/cipriantarta/django-logging/blob/master/setup.py#L49).
This currently breaks the library for us 😞

**Comment by cipriantarta** [comment]
Damn it :)
Well, I'll do an upgrade to setup requirements, but meanwhile you can add certifi to your requirements.txt to make this work

**Comment by cipriantarta** [comment]
I added certifi as a requirement in 1.14
