### ISSUE TITLE
Python 3.9 and exception traceback handling

### ISSUE THREAD

**Issue by chigby** [cipriantarta/django-logging#21]
So, python 3.9 changes some of the attributes of `traceback.TracebackException` which is being used here to get stack trace information in [`ErrorLogObject`](https://github.com/cipriantarta/django-logging/blob/033db3f8c117788c97d172d6802e273f33de8dde/django_logging/log_object.py#L105). Namely, the `exc_traceback` attribute has been removed. Fortunately, there is another way to get the same information, but the code as written right now will not work under python 3.9.

One possible example of how to re-write it for compatibility, though the code here removes support for python 3.4 and older: https://github.com/freedomofpress/django-logging/pull/6

**Comment by cipriantarta** [comment]
@chigby I no longer use this library, or Python for that matter. If you want to update it to support `3.9`, I'm happy to merge it.

**Comment by chigby** [comment]
Ah, thanks for the reply. In that case, probably better to leave this repo as-is.
