### ISSUE TITLE
Is it possible to configure json structure?

### ISSUE THREAD

**Issue by heytrav** [cipriantarta/django-logging#3]
Is there any way to configure the JSON output? My company's ELK  cluster expects certain fields to have specific names/datatypes in order to be processed by logstash plugins. For example:

```
 { 
    "timestamp": "2017-01-03T18:46:06Z", # has to be ISO8601
    "loglevel": "debug|info|...",
    "clientip": "192.168.1.1", # for geoip
    "otherfields": {
              .
              .
 }
```

**Comment by cipriantarta** [comment]
I'm not sure, let me have a look and get back at you, but theoretically it should be possible.

**Comment by cipriantarta** [comment]
@heytrav currently you can only set the response fields available in the django HttpResponse object.
This can probably be customized, but requires some substantial work where one could be able to specify the "LogObject" that they want to use. When time allows, I will add support for that.
