### ISSUE TITLE
Can we disable logging while DEBUG = False ?

### ISSUE THREAD

**Issue by murtuzamvista** [cipriantarta/django-logging#7]
Logging each request and response in production would make responses slower. Is it possible to disable logging to file while in prod environment? I want to use this plugin for logging in dev/staging environment for debugging purposes.

**Comment by cipriantarta** [comment]
In theory, logging should not make responses slower. It's usually done in another thread. 
If that's the case, it's a bug and we should probably take care of it.
On the same note, requests are logged using this middleware: https://github.com/cipriantarta/django-logging/blob/master/django_logging/middleware.py
You can just remove the middleware, or set LOG_LEVEL to warn, or create a PR that gives you the option to not log response/request if a custom setting variable is set("LOG_REQUESTS=False" for example).
